version: "3.2"
services:
  mssql:
    image: 'microsoft/mssql-server-linux'
    build: ./src/main/mssql
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    volumes:
      - database-data:/var/opt/mssql
  api:
    build: ./src/main/docker
    expose:
      - '8080'
    depends_on:
      - mssql
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=sdp
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Secret1234

  frontend:
    image: "php:7.4-apache"
    container_name: frontend
    restart: always
    depends_on:
      - api
    ports:
      - "9000:80"
    volumes:
      - ./web:/var/www/html

  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src/main/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
volumes:
  database-data:
